alias ls='ls -G'
alias sub='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias cls='clear && ls'
alias list='~/Documents/glassrooms/glassrooms.sh list'
alias book='~/Documents/glassrooms/glassrooms.sh book'
alias cancel='~/Documents/glassrooms/glassrooms.sh cancel'
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.cabal/bin
export EDITOR='emacs'
