alias ls='ls -G'
alias cls='clear && ls'
alias emacs='/Applications/Emacs.app/Contents/MacOS/Emacs "$@"'
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.cabal/bin
export EDITOR='vim'
export GOPATH=$HOME/Go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
